import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="flex items-center justify-end space-x-4 px-4 py-2 bg-slate-300">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/contact">Contact</Link>
            <Link href={"/profile"}>Profile</Link>
            <Link href={"/profile/details"}>Profile Details</Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
